all:
	g++  -o "FantasyFootballConverter"  ./Debug/src/Drive.o ./Debug/src/FantasyFootball1.o ./Debug/src/Game.o ./Debug/src/Play.o ./Debug/src/PlayPoints.o ./Debug/src/Players.o ./Debug/src/PointCalculator.o ./Debug/src/Team.o 

run:
	./FantasyFootballConverter
